
all: base_arrow_down base_arrow_up boat bottom_left_corner bottom_right_corner bottom_side bottom_tee center_ptr circle cross dot_box_mask dot draped_box exchange fleur gumby hand1 hand2 left_ptr left_ptr_watch left_side left_tee ll_angle lr_angle pencil pirate right_ptr right_side right_tee sailboat shuttle sizing target top_left_corner top_right_corner top_side top_tee trek ul_angle ur_angle watch X_cursor xterm

base_arrow_down: base_arrow_down.conf base_arrow_down_001.png
	xcursorgen base_arrow_down.conf > base_arrow_down
base_arrow_up: base_arrow_up.conf base_arrow_up_001.png
	xcursorgen base_arrow_up.conf > base_arrow_up
boat: boat.conf boat_001.png
	xcursorgen boat.conf > boat
bottom_left_corner: bottom_left_corner.conf bottom_left_corner_001.png
	xcursorgen bottom_left_corner.conf > bottom_left_corner
bottom_right_corner: bottom_right_corner.conf bottom_right_corner_001.png
	xcursorgen bottom_right_corner.conf > bottom_right_corner
bottom_side: bottom_side.conf bottom_side_001.png
	xcursorgen bottom_side.conf > bottom_side
bottom_tee: bottom_tee.conf bottom_tee_001.png
	xcursorgen bottom_tee.conf > bottom_tee
center_ptr: center_ptr.conf center_ptr_001.png
	xcursorgen center_ptr.conf > center_ptr
circle: circle.conf circle_001.png
	xcursorgen circle.conf > circle
cross: cross.conf cross_001.png
	xcursorgen cross.conf > cross
dot_box_mask: dot_box_mask.conf dot_box_mask_001.png
	xcursorgen dot_box_mask.conf > dot_box_mask
dot: dot.conf dot_001.png
	xcursorgen dot.conf > dot
draped_box: draped_box.conf draped_box_001.png
	xcursorgen draped_box.conf > draped_box
exchange: exchange.conf exchange_001.png
	xcursorgen exchange.conf > exchange
fleur: fleur.conf fleur_001.png
	xcursorgen fleur.conf > fleur
gumby: gumby.conf gumby_001.png
	xcursorgen gumby.conf > gumby
hand1: hand1.conf hand1_001.png
	xcursorgen hand1.conf > hand1
hand2: hand2.conf hand2_001.png
	xcursorgen hand2.conf > hand2
left_ptr: left_ptr.conf left_ptr_001.png
	xcursorgen left_ptr.conf > left_ptr
left_ptr_watch: left_ptr_watch.conf left_ptr_watch_001.png
	xcursorgen left_ptr_watch.conf > left_ptr_watch
left_side: left_side.conf left_side_001.png
	xcursorgen left_side.conf > left_side
left_tee: left_tee.conf left_tee_001.png
	xcursorgen left_tee.conf > left_tee
ll_angle: ll_angle.conf ll_angle_001.png
	xcursorgen ll_angle.conf > ll_angle
lr_angle: lr_angle.conf lr_angle_001.png
	xcursorgen lr_angle.conf > lr_angle
pencil: pencil.conf pencil_001.png
	xcursorgen pencil.conf > pencil
pirate: pirate.conf pirate_001.png
	xcursorgen pirate.conf > pirate
right_ptr: right_ptr.conf right_ptr_001.png
	xcursorgen right_ptr.conf > right_ptr
right_side: right_side.conf right_side_001.png
	xcursorgen right_side.conf > right_side
right_tee: right_tee.conf right_tee_001.png
	xcursorgen right_tee.conf > right_tee
sailboat: sailboat.conf sailboat_001.png
	xcursorgen sailboat.conf > sailboat
shuttle: shuttle.conf shuttle_001.png
	xcursorgen shuttle.conf > shuttle
sizing: sizing.conf sizing_001.png
	xcursorgen sizing.conf > sizing
target: target.conf target_001.png
	xcursorgen target.conf > target
top_left_corner: top_left_corner.conf top_left_corner_001.png
	xcursorgen top_left_corner.conf > top_left_corner
top_right_corner: top_right_corner.conf top_right_corner_001.png
	xcursorgen top_right_corner.conf > top_right_corner
top_side: top_side.conf top_side_001.png
	xcursorgen top_side.conf > top_side
top_tee: top_tee.conf top_tee_001.png
	xcursorgen top_tee.conf > top_tee
trek: trek.conf trek_001.png
	xcursorgen trek.conf > trek
ul_angle: ul_angle.conf ul_angle_001.png
	xcursorgen ul_angle.conf > ul_angle
ur_angle: ur_angle.conf ur_angle_001.png
	xcursorgen ur_angle.conf > ur_angle
watch: watch.conf watch_*.png
	xcursorgen watch.conf > watch
X_cursor: X_cursor.conf X_cursor_001.png
	xcursorgen X_cursor.conf > X_cursor
xterm: xterm.conf xterm_001.png
	xcursorgen xterm.conf > xterm
