// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200403170909");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.user_id", "76ea324f-5a1d-4006-a6f2-0eff8eada9f2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1586825785);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1586826070);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1586825905);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1586825815);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 16408);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1586825755);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5602adb6-44cf-41ec-8367-85b99cdf100e}");
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1586825816331");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1586827588331");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1586825759248");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1586829359248");
user_pref("browser.search.region", "BR");
user_pref("browser.search.widget.inNavBar", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200403170909");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1586826141");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1586826141);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"search-container\",\"downloads-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-mnnxcxisbpnsxq_jetpack-browser-action\",\"https-everywhere_eff_org-browser-action\",\"_contain-facebook-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.update1", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1586825758049");
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "a167168d76e943ffa0ab7183ee7f3ce6");
user_pref("extensions.activeThemeID", "{77fa8e30-5152-44e3-8dd5-e76f853f16dd}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403170909");
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.@contain-facebook", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.https-everywhere@eff.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-MnnxcxisBPnSXQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d5d3caf6-6aba-425d-9cfd-310aa021bd4b\",\"formautofill@mozilla.org\":\"033275c0-6df0-4add-b5bb-3b940d7399c6\",\"screenshots@mozilla.org\":\"da9e5601-c0f0-4b2c-9fa0-73eccadeb4e9\",\"webcompat-reporter@mozilla.org\":\"8a681966-64fb-44b6-a966-3bdb3989577a\",\"webcompat@mozilla.org\":\"b5690779-2ffc-438c-bcc0-ca9c2ae43e27\",\"default-theme@mozilla.org\":\"e55ba2a3-86cc-478e-9b7f-03caa5c1656f\",\"google@search.mozilla.org\":\"149c79db-3fbe-450e-ae38-992c9818c0fb\",\"amazondotcom@search.mozilla.org\":\"e679b209-0377-4329-9bb6-55ced7f253bd\",\"bing@search.mozilla.org\":\"b7582042-14c0-4cf0-8e16-bfbaeabcfddc\",\"ddg@search.mozilla.org\":\"628197ae-7c57-4dde-a651-f8a3d3314ac4\",\"ebay@search.mozilla.org\":\"ddbc8e29-bb20-42cc-8b19-4b4bf3df75b7\",\"twitter@search.mozilla.org\":\"f94cd770-ce23-4dde-a64e-45734a1c72b1\",\"wikipedia@search.mozilla.org\":\"e20be63f-67e0-45d8-8c41-acab530def72\",\"{77fa8e30-5152-44e3-8dd5-e76f853f16dd}\":\"a6599043-4542-4856-8847-76e667442c68\",\"jid1-MnnxcxisBPnSXQ@jetpack\":\"68215489-2256-4367-b63b-2b75a2b36121\",\"https-everywhere@eff.org\":\"32fe55be-f1cc-4f18-b298-e029acdc955f\",\"@contain-facebook\":\"44cf6b90-10b6-4ec0-81f7-6a4d4027475d\",\"uBlock0@raymondhill.net\":\"f9cc978d-9215-4221-8f6d-b16f3f356409\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.extension", "@contain-facebook");
user_pref("privacy.userContext.ui.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "31a5edc9-be38-4ee3-9230-81f647320cf7");
user_pref("security.sandbox.plugin.tempDirSuffix", "d79e9dd0-3fa5-4a9b-a709-3161aeb87247");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1586826140);
user_pref("toolkit.telemetry.cachedClientID", "8cf820da-82d9-42da-aa57-e75b73328f25");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.key.menuAccessKeyFocuses", false);
